version: '3.8'

services: 
    express: 
        container_name: 'express'
        build: ./express/
        ports: 
            - 8080:8080
        volumes: 
            - "./express:/usr/src/app"
            - /usr/src/app/node_modules/